### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by xanderyzwich** [codeconnector/py_unittest_walkthrough#1]
From Slack chat:

To see how it works, if you have python3x installed you can run individual tests by:

cd test
cd unit_tests
python3 utils_test.py
python3 core_test.py

You can get code coverage by:

cd test
./run_coverage.sh

**Comment by rjbeers** [comment]
I recommend having a description of what this repository is as well.

**Comment by drkennetz** [comment]
Completed with 9a62ce6
