### ISSUE TITLE
Extraneous files were committed

### ISSUE THREAD

**Issue by rjbeers** [codeconnector/py_unittest_walkthrough#6]
This repository has many files that appear to be temp files created by an editor and accidentally committed to git. Files ending in `~` should be removed.

**Comment by ernestoarbitrio** [comment]
I'd like to work on this! Do you need to assign it to me or i can just start working on this issue?

**Comment by drkennetz** [comment]
@ernestoarbitrio hi Ernesto, fork the repo, make changes, and create a PR when you feel like it is complete.

**Comment by ernestoarbitrio** [comment]
k thx

**Comment by ernestoarbitrio** [comment]
https://github.com/codeconnector/py_unittest_walkthrough/pull/7 <- here
